name: Deploy Build

on: 
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build using Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: | 
        yarn
        rm .gitignore
        rm -r ./build/*
    - name: Lint
      run: yarn lint
    - name: Build project
      run: yarn build
    - name: Commit Build
      uses: EndBug/add-and-commit@v7.2.1
      with:
        # The arguments for the `git add` command (see the paragraph below for more info)
        # Default: '.'
        add: './build --force'
    
        # Name of the branch to use, if different from the one that triggered the workflow
        # Default: the branch that triggered the run
        branch: dev

        # Determines the way the action fills missing author name and email. Three options are available:
        # - github_actor -> UserName <UserName@users.noreply.github.com>
        # - user_info -> Your Display Name <your-actual@email.com>
        # - github_actions -> github-actions <email associated with the github logo>
        # Default:
        default_author: github_actions

        # The message for the commit
        # Default: 'Commit from GitHub Actions (name of the workflow)'
        message: 'Deploy Build'
